# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: pulpcore-selinux.spec

# add or remove files that should be synced
files_to_sync:
  - pulpcore-selinux.spec
  - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: pulpcore-selinux
# downstream (Fedora) RPM package name
downstream_package_name: pulpcore-selinux

upstream_tag_template: "{version}"

actions:
  post-upstream-clone:
    - "wget https://raw.githubusercontent.com/theforeman/pulpcore-packaging/rpm/develop/packages/pulpcore-selinux/pulpcore-selinux.spec -O pulpcore-selinux.spec"
  get-current-version:
    - bash -c "grep '^policy_module' pulpcore.te | tr -c -d '[0-9.]'"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      rhel-9: {}
      rhel-10: {}

srpm_build_deps:
  - wget
